### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by John-doe-lee** [JPomichael/atom-chs-menu#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package 1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:472

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at delay (/packages/atom-chs-menu/lib/main.coffee:7:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-chs-menu 1.0.0 
atom-monokai 0.10.9 
monokai 0.22.0 
```

**Comment by ydxred** [comment]
win也遇到同样的问题

**Comment by ydxred** [comment]
Win also encountered the same problem solving

**Comment by junib2000** [comment]
how to  solve?  help! I have the same problem。

**Comment by junib2000** [comment]
问题找到了：atom-chs-menu 是功能选项菜单和鼠标右键功能汉化插件。 先安装另外一个汉化插件“simplified-chinese-menu”后，再关闭该“atom-chs-menu”插件。错误信息消失。

**Comment by Herycdd** [comment]
按照楼上的说法我把atom-chs-menu卸载掉就正常了电力效果也可以用了
