### ISSUE TITLE
在最新版的atom中运行报错

### ISSUE THREAD

**Issue by icimence** [JPomichael/atom-chs-menu#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package 1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:545

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at delay (/packages/atom-chs-menu/lib/main.coffee:7:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
def undefined 
lib undefined 
screenshot undefined 
tools undefined 
```

**Comment by icimence** [comment]
Cannot load the system dictionary for zh-CN. Checked the following paths for dictionary files:

C:\
C:\Users\icimence\AppData\Local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries
