### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by PengXialan** [JPomichael/atom-chs-menu#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 ia32
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package 1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'cson'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (D:/迅雷下载/atom-windows/Atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (D:/迅雷下载/atom-windows/Atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (D:/迅雷下载/atom-windows/Atom/resources/app/static/<embedded>:11:146745)
    at delay (/packages/atom-chs-menu/lib/main.coffee:7:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
```

**Comment by marklove5102** [comment]
npm install --save cson
