### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by Ray-Jean** [JPomichael/atom-chs-menu#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package 1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'cson'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at delay (/packages/atom-chs-menu/lib/main.coffee:7:12)
```

### Commands

```
     -6:35.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:11.8.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -5:07.8.0 core:backspace (input.hidden-input)
     -5:02.1.0 core:confirm (input.hidden-input)
     -4:57.9.0 autocomplete-plus:confirm (input.hidden-input)
     -4:57.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:29.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
```

**Comment by marklove5102** [comment]
npm install --save cson
