### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by zhump** [JPomichael/atom-chs-menu#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package, v1.0.0
### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:341

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Users/zhumingpeng/Documents/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Users/zhumingpeng/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports.delay (/Users/zhumingpeng/.atom/packages/atom-chs-menu/lib/main.coffee:7:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.4.1 (inactive)
atom-beautify, v0.28.28 (inactive)
atom-chs-menu, v1.0.0 (active)
atom-html-preview, v0.1.19 (active)
atom-react-native-autocomplete, v0.0.7 (active)
atom-react-native-css, v0.0.6 (active)
emmet, v2.4.3 (active)
language-javascript-jsx, v0.3.7 (inactive)
minimap-find-and-replace, v4.5.0 (active)
open-in-browser, v0.4.6 (inactive)
react, v0.15.0 (inactive)
react-es6-snippets, v0.3.0 (active)
react-snippets, v0.4.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by smartwange** [comment]
Is  there has any  answer ?  Please

**Comment by yfgeek** [comment]
@smartwange @zhump You should install cson by the command shell:
npm install --save cson 

Good luck!

**Comment by orangeWater** [comment]
Error: Cannot find module 'cson'

**Comment by zhangdong1104** [comment]
Hello! How do you do that?

**Comment by yuhongHo** [comment]
install to which dir??

**Comment by JPomichael** [comment]
try   
 ``` 
npm install --save cson
```

**Comment by dockercore** [comment]
erreor

**Comment by dockercore** [comment]
tty Hello! How do you do that?  erreor????? erreor???

**Comment by dockercore** [comment]
Uncaught Error: Cannot find module 'cson'

**Comment by dockercore** [comment]
[``](url)Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'
Uncaught Error: Cannot find module 'cson'

**Comment by poyun** [comment]
it's ok!
