### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'Require stack:- $ATOM_HOME/packages\atom-chs-menu\lib\...

### ISSUE THREAD

**Issue by weijiening** [JPomichael/atom-chs-menu#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-chs-menu](https://github.com/JPomichael/atom-chs-menu) package 1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'cson'
Require stack:
- C:\Users\weijn\.atom\packages\atom-chs-menu\lib\main.coffee
- C:\Users\weijn\Downloads\Atom x64\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'cson'
Require stack:
- C:\Users\weijn\.atom\packages\atom-chs-menu\lib\main.coffee
- C:\Users\weijn\Downloads\Atom x64\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/Downloads/Atom x64/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/Downloads/Atom x64/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/Downloads/Atom x64/resources/app/static/<embedded>:11:146814)
    at delay (/packages/atom-chs-menu/lib/main.coffee:7:12)
```

### Commands

```
     -1:16.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
```

**Comment by yangxin1994** [comment]
请问还没有解决么，我现在也遇到这个问题了

**Comment by yangxin1994** [comment]
Is it still solved yet? I have also encountered this problem now.
