### ISSUE TITLE
兄弟，1,11.2版本好像不能用了

### ISSUE THREAD

**Issue by hurrypp** [JPomichael/atom-chs-menu#4]
刚更新到1.11.2的版本，安装汉化包报错
Uncaught Error: Cannot find module 'cson'

---

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports.delay (/home/pl/.atom/packages/atom-chs-menu/lib/main.coffee:7:12)

**Comment by JPomichael** [comment]
好的 谢谢反馈 我会跟进下

**Comment by yfgeek** [comment]
在系统中执行 npm install --save cson
